version: "3"
services:
  notebook:
    image: jupyter/scipy-notebook:latest
    command: jupyter notebook --NotebookApp.token='' --ServerApp.token=''
    working_dir: /jupyter
    volumes:
      - ".:/jupyter"
    ports:
      - "8888:8888"
  mercury:
    build:
      context: .
    ports:
      - "8000:8000"